version: '3.3'

services:
  mysql-service-db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      # 下面的环境变量可以创建数据库和新用户
      # MYSQL_DATABASE: test_db
      # MYSQL_USER: test
      # MYSQL_PASSWORD: 123456
    networks: 
      - default_tier
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 60s
      retries: 10

  mysql-service-admin:
    depends_on: 
      mysql-service-db:
        condition: service_healthy
    image: phpmyadmin/phpmyadmin
    container_name: mysql_admin
    ports: 
      - "8080:80"
    environment: 
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      # 配置了下面两个环境变量的话，访问mysql_admin，将跳过登录环节
      # PMA_USER: root
      # PMA_PASSWORD: 123456
    restart: always
    networks: 
      - default_tier

volumes:
  db_data: {}

networks: 
  default_tier:
    driver: bridge  