version: '3.3'

services:
  nocodb-service-db:
    image: postgres
    container_name: nocodb_postgres
    restart: always
    ports: 
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: noco
      POSTGRES_DB: noco_db
    networks: 
      - default_tier
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
  nocodb-service-app:
    depends_on:
      nocodb-service-db:
        condition: service_healthy
    image: nocodb/nocodb:latest
    container_name: nocodb_app
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    restart: always
    environment:
      NC_DB: "pg://nocodb_postgres:5432?u=noco&p=123456&d=noco_db"
    networks: 
      - default_tier
volumes:
  postgres_data: {}

networks: 
  default_tier:
    driver: bridge  